/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimateBanner: typeof import('./src/components/animateBanner/index.vue')['default']
    Background: typeof import('./src/components/background/index.vue')['default']
    Ball: typeof import('./src/components/ball/index.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HeaderRight: typeof import('./src/components/topHeader/headerRight.vue')['default']
    HomeCards: typeof import('./src/components/homeCards/index.vue')['default']
    Paryicles: typeof import('./src/components/paryicles/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopHeader: typeof import('./src/components/topHeader/index.vue')['default']
  }
}
